### ISSUE TITLE
[GCC] PAD: Testar Testes Continuos

### ISSUE THREAD

**Issue by joaomas** [monanadmin/monan#442]
## :people_holding_hands: User Story

COMO Saulo,
QUEREMOS Testar os Testes Contínuos,
PARA Manter a qualidade da entrega.

## :clipboard: Critérios de aceite de conclusão da Issue

- [ ] ~~Saídas validadas após as nova versão 0.2.0 (variáveis níveis)~~
- [x] Saídas validadas conforme #438 e #441 (usando branch develop do Modelo e Scripts)

## :pencil: Detalhamento adicional da atividade

Corrigir possíveis erros, como esquecimento de variáveis, remoção de variáveis que não funcionam.

## :comet: Impactos

N.A

## :link: Dependências

- #441 

## :hammer_and_wrench: Solução

TC executando diariamente com alterações desde 16/03.

- [x] Variáveis incluídas no Registry.xml do MONAN-Model e em stream_list.atmosphere.diagnostics no MONAN-scripts de acordo com documentação gdocs da #438 

- [x] Saída do modelo validada de acordo com documentação gdocs da #438. 
[vars_saida_modelo.txt](https://github.com/monanadmin/monan/files/14635955/vars_saida_modelo.txt)

- [x] Saída do pós processamento validada
![image](https://github.com/monanadmin/monan/assets/6113640/8c2f48ef-5cd8-4fe5-a351-d067c7c943e8)

## :rotating_light: Problemas encontrados

N.A

## :white_check_mark: Conclusão

Saídas do modelo e pós validadas com algumas variáveis faltantes a serem implementadas no modelo ou no pós.

## :spiral_calendar: Trabalhos Futuros

Verificar variáveis faltantes a serem implementadas no modelo ou no pós. Verificar se o mesmo trabalho futuro já não está descrito nas tarefas #438 ou #441

**Comment by joaomas** [comment]
Trabalho futuro já um requisito intrínseco do teste ("saídas validadas")
